apiVersion: v1
kind: Pod
metadata:
  labels:
    app/name: hello-world
  name: hello-world
spec:
  containers:
    - image: nginxdemos/hello
      name: nginx
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app/name: hello-world
  name: hello-world
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app/name: hello-world
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 80